/*
code → String, unique code for the discount.
expirationDate → Date, when the coupon becomes invalid.
discountPercentage → Number, percentage discount (e.g., 10 for 10%).
usedBy[] → Array of User IDs who have used this coupon.
createdAt / updatedAt → Timestamps automatically generated by Mongoose.
*/