/*
code → String, unique code for the discount.
expirationDate → Date, when the coupon becomes invalid.
discountPercentage → Number, percentage discount (e.g., 10 for 10%).
usedBy[] → Array of User IDs who have used this coupon.
createdAt / updatedAt → Timestamps automatically generated by Mongoose.
*/
const mongoose = require('mongoose');

const couponSchema = new mongoose.Schema(
    {
        code: {
            type: String,
            required: true,
            unique: true,
            trim: true
        },

        expirationDate: {
            type: Date,
            required: true
        },

        discountPercentage: {
            type: Number,
            required: true,
            min: 0,
            max: 100
        },

        usedBy: [
            {
                type: mongoose.Schema.Types.ObjectId,
                ref: 'User'
            }
        ]
    },
    {
        timestamps: true // createdAt & updatedAt
    }
);

module.exports = mongoose.model('Coupon', couponSchema);