/*
clientId → Reference to the User who is making the consultation request.
lawyerId → Reference to the User who is the lawyer for this consultation.
subject → String, main topic of the consultation.
message → String, detailed description or question from the client.
attachments[] → Array of file URLs or filenames (optional supporting documents).
price → Number, cost of the consultation.
taxes → Number, any applicable taxes on the price.
couponCode → String, optional coupon applied for discount.
status → String, enum: pending, accepted, refused (default: pending).
scheduledDate → Date, the day of the consultation.
scheduledSlot → String, the specific time slot chosen (e.g., "10:00").
createdAt / updatedAt → Timestamps automatically generated by Mongoose.
*/