/*
clientId → Reference to the User who is making the consultation request.
lawyerId → Reference to the User who is the lawyer for this consultation.
subject → String, main topic of the consultation.
message → String, detailed description or question from the client.
attachments[] → Array of file URLs or filenames (optional supporting documents).
price → Number, cost of the consultation.
taxes → Number, any applicable taxes on the price.
couponCode → String, optional coupon applied for discount.
status → String, enum: pending, accepted, refused (default: pending).
scheduledDate → Date, the day of the consultation.
scheduledSlot → String, the specific time slot chosen (e.g., "10:00").
createdAt / updatedAt → Timestamps automatically generated by Mongoose.
*/




/*--------------------------------------Starting work--------------------------------------*/



const mongoose = require("mongoose");

const isticharaSchema = new mongoose.Schema(
  {
    clientId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "User",
      required: true
    },

    lawyerId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "User",
      required: true
    },

    subject: {
      type: String,
      required: true,
      trim: true
    },

    message: {
      type: String,
      required: true
    },

    attachments: [
      {
        type: String
      }
    ],

    price: {
      type: Number,
      default: 0
    },

    taxes: {
      type: Number,
      default: 0
    },

    couponCode: {
      type: String,
      default: null
    },

    status: {
      type: String,
      enum: ["pending", "accepted", "refused"],
      default: "pending"
    },

    scheduledDate: {
      type: Date,
      required: true
    },

    scheduledSlot: {
      type: String,
      required: true
    }
  },
  { timestamps: true }
);

module.exports = mongoose.model("Istichara", isticharaSchema);