/*
lawyerId → Reference to the User (lawyer) being reviewed.
clientId → Reference to the User (client) leaving the review.
rating → Number (1–5), the score given by the client.
comment → String, optional text comment from the client.
createdAt / updatedAt → Timestamps automatically generated by Mongoose.
*/

const mongoose = require('mongoose');

const reviewSchema = new mongoose.Schema(
    {
        lawyerId: {
            type: mongoose.Schema.Types.ObjectId,
            ref: 'User',
            required: true
        },
        clientId: {
            type: mongoose.Schema.Types.ObjectId,
            ref: 'User',
            required: true
        },
        rating: {
            type: Number,
            required: true,
            min: 1,
            max: 5
        },
        comment: {
            type: String,
            default: ''
        }
    },
    {
        timestamps: true
    }
);

module.exports = mongoose.model('Review', reviewSchema);