/*
lawyerId → Reference to the User (lawyer) being reviewed.
clientId → Reference to the User (client) leaving the review.
rating → Number (1–5), the score given by the client.
comment → String, optional text comment from the client.
createdAt / updatedAt → Timestamps automatically generated by Mongoose.
*/